# Generated by Django 5.2.1 on 2025-08-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the person', max_length=200)),
                ('email', models.EmailField(help_text='Email address for response', max_length=254)),
                ('subject', models.CharField(help_text='Subject of the message', max_length=300)),
                ('message', models.TextField(help_text='The actual message content')),
                ('phone', models.CharField(blank=True, help_text='Optional phone number', max_length=20)),
                ('company', models.CharField(blank=True, help_text='Optional company name', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, help_text='Mark as read')),
                ('is_replied', models.BooleanField(default=False, help_text='Mark as replied')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
